version: "3"

services:
  mysql:
    image: mysql:5.7.29
    environment:
      MYSQL_DATABASE: experimental
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
    - 3306:3306